version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: check files
          command: ls
      - run:
          name: check pwd
          command: pwd
      - save_cache:
          key:  dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: install libraries
          command: apt-get install -y libgtk-3.0 libgbm-dev libnss3 libatk-bridge2.0-0 libasound2
      - run:
          name: unit test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test